use_frameworks!

platform :ios, '8.0'

target 'EWSpeechText_Example' do
  pod 'EWSpeechText', :path => '../'

  target 'EWSpeechText_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
